version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8000'
    environment:
      - VIRTUAL_HOST=telehire.dronicho.ru
      - VIRTUAL_PORT=5173
